FROM python:3.11-slim

WORKDIR /app

COPY ingestor/requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY ingestor/ .

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        netcat-openbsd \
        iputils-ping \
        procps \
    && rm -rf /var/lib/apt/lists/*


CMD ["/app/rag-ingestor_cli.py", "store"]
